services:
  - type: web
    name: solve-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
  - type: worker
    name: solve-job-worker
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run worker
